# Generated by Django 5.1.1 on 2024-10-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
